host = 'www.ws.amq.idug2016.link';      // hostname or IP address               
port = 80                                                                       
topic = 'mqtt/SensorTag';       // topic to subscribe to                          
//queue = 'testing/Q1'                                                          
useTLS = false;                                                                 
username = "admin";                                                             
password = "admin";                                                             
// username = "devan";                                                          
// password = "devan123";                                                       
cleansession = true;       
